import React, { useState } from 'react';
import { Target, AlertCircle, RefreshCw } from 'lucide-react';
import { api } from '../lib/api';
import { LoadingState } from '../components/ui/LoadingState';
import { StatusBadge } from '../components/ui/StatusBadge';
import { SectionDivider } from '../components/ui/SectionDivider';
import { DecoButton } from '../components/ui/DecoButton';

export default function Eligibility() {
  const [company, setCompany] = useState('');
  const [role, setRole] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);
  const [error, setError] = useState('');

  const run = async () => {
    if (!company.trim() || !role.trim()) {
      setError('Please enter both target company and role.');
      return;
    }
    setLoading(true);
    setError('');
    setResult(null);
    try {
      const data = await api.analysis.eligibility({ targetCompany: company, targetRole: role });
      setResult(data);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="p-4 md:p-6 space-y-5 animate-fade-in">
      <div>
        <div className="label-deco mb-1">AI-powered placement eligibility analysis</div>
        <h1 className="font-heading text-xl text-foreground tracking-wide">ELIGIBILITY ANALYSIS</h1>
      </div>

      <SectionDivider />

      {/* Input */}
      <div className="deco-card deco-corners p-4">
        <div className="label-deco mb-4">Target Position</div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4">
          <div>
            <label htmlFor="elig-company" className="input-label">Target Company *</label>
            <input
              id="elig-company"
              className="input-deco"
              placeholder="e.g. Google, Infosys, TCS"
              value={company}
              onChange={e => setCompany(e.target.value)}
            />
          </div>
          <div>
            <label htmlFor="elig-role" className="input-label">Target Role *</label>
            <input
              id="elig-role"
              className="input-deco"
              placeholder="e.g. Software Engineer, Data Analyst"
              value={role}
              onChange={e => setRole(e.target.value)}
            />
          </div>
        </div>

        <div className="p-3 border border-[#1E1E1E] text-muted text-xs leading-relaxed mb-4">
          <span className="text-gold font-semibold">Note:</span> The AI analysis is powered by Azure AI Foundry and uses your complete profile — academic details, skills, projects, certifications, and uploaded resume.
          Eligibility is never guaranteed. Results distinguish: <em>Satisfied</em>, <em>Information Missing</em>, and <em>Confirmed Skill Gap</em>.
        </div>

        {error && (
          <div className="flex items-center gap-2 p-3 mb-3 border border-red-800/50 bg-red-900/10 text-red-400 text-xs">
            <AlertCircle size={14} />
            <span>{error}</span>
          </div>
        )}

        <DecoButton
          id="run-eligibility"
          onClick={run}
          loading={loading}
          icon={<Target size={14} />}
        >
          {loading ? 'Analyzing Placement Requirements...' : 'Run Eligibility Analysis'}
        </DecoButton>
      </div>

      {/* Loading */}
      {loading && (
        <div className="deco-card p-8">
          <LoadingState message="Analyzing placement requirements..." size="lg" />
          <p className="text-center text-muted text-xs mt-3">
            The AI agent is reviewing your profile against {company}'s requirements for {role}.
          </p>
        </div>
      )}

      {/* Result */}
      {result && !loading && (
        <div className="deco-card deco-corners p-4 animate-slide-up space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
            <div>
              <div className="label-deco mb-1">Analysis Result</div>
              <div className="font-heading text-base text-foreground">
                {company} — {role}
              </div>
            </div>
            <div className="flex items-center gap-2">
              <StatusBadge variant="gold">Eligibility Analysis</StatusBadge>
              <button onClick={run} className="btn-ghost !p-2 !min-h-0" aria-label="Re-run analysis">
                <RefreshCw size={12} />
              </button>
            </div>
          </div>

          <SectionDivider />

          <div className="prose-deco" dangerouslySetInnerHTML={{ __html: formatAnalysis(result.analysis) }} />

          <div className="pt-2 border-t border-[#2A2A2A]">
            <p className="text-muted text-[10px] italic">
              Analysis generated by Azure AI Foundry (CampusPlacementAgent) on {new Date(result.timestamp).toLocaleString()}.
              This analysis does not guarantee placement selection.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}

function formatAnalysis(text: string): string {
  if (!text) return '';
  return text
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br/>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/^# (.+)$/gm, '<h2>$1</h2>')
    .replace(/^## (.+)$/gm, '<h3>$1</h3>')
    .replace(/^### (.+)$/gm, '<h4>$1</h4>')
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>)/s, '<ul>$1</ul>');
}
